name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Compilar aplicativo
        run: npm run build

      - name: Disponibilizar EXE
        uses: actions/upload-artifact@v4
        with:
          name: Treinos-SP-Windows
          path: dist/*.exe
